### ISSUE TITLE
Classes nested inside functions are not transformed

### ISSUE THREAD

**Issue by abierbaum** [goloveychuk/tsruntime#11]
Added an example in PR: https://github.com/goloveychuk/tsruntime/pull/10

A simple example that doesn't work is:

```
describe('Custom Decorators', () => {
   it('should work nested', () => {
      @Reflective
      class InnerClass {
          a: string;
      }

      const clsType = getType(InnerClass);
      // fails: expect(clsType).toBeDefined();
   });
});
```

the issue seems to be that the transformer only examines classes at the root of the source file.

**Comment by abierbaum** [comment]
Tried a quick fix and looks like it worked: https://github.com/goloveychuk/tsruntime/pull/10

**Comment by abierbaum** [comment]
Tried:

```
function visitor(node: ts.Node): ts.VisitResult<ts.Node> {
     onBeforeVisitNode(node)
     switch (node.kind) {
        case ts.SyntaxKind.ClassDeclaration:
          return visitClassDeclaration(<tse.ClassDeclaration>node)
        default:
 -        return node
 +        return ts.visitEachChild(node, visitor, context);
      }
    }
```

But it leads to failures like the one below when used with more complex code.  Guessing there are some types of nodes we should not go into:

```
[at-loader]: Child process failed to process the request:  Error: Debug Failure. False expression: Lexical environment is already suspended.
    at Object.assert (/home/allenb/Source/taccs/web2/node_modules/typescript/lib/typescript.js:3323:23)
    at Object.suspendLexicalEnvironment (/home/allenb/Source/taccs/web2/node_modules/typescript/lib/typescript.js:61442:22)
    at visitParameterList (/home/allenb/Source/abierbaum_tsruntime/node_modules/typescript/lib/typescript.js:47474:17)
    at Object.visitEachChild (/home/allenb/Source/abierbaum_tsruntime/node_modules/typescript/lib/typescript.js:47676:338)
    at visitor (/home/allenb/Source/abierbaum_tsruntime/src/transformer.ts:280:19)
```

so still an open bug.

**Comment by goloveychuk** [comment]
yea, it's because you visited function arguments node. which have other api.

**Comment by goloveychuk** [comment]
should be fixed
